Add debian stretch and buster
jlesage/docker-baseimage pull request #3
Opened 2018-05-09 07:59 UTC by rollbrettler

2018-05-22 11:17 UTC, rollbrettler commented
@jlesage Do you think this change is valuable?

2018-05-22 12:38 UTC, jlesage commented
Sorry it seems that this one fallen into the cracks.

While I agree to add  debian stretch, I'm not sure about the non-stable buster version.  Could you adjust the pull request to only include debian stretch?

2018-05-25 06:05 UTC, rollbrettler commented
Is your concern the additional maintenance if buster breaks?

I see it as a preparation for the next release, but have no hard feelings about it, would just like to have more context.

Thanks.

2018-05-25 09:34 UTC, jlesage commented
I prefer to offer baseimages based on stable releases.  Like you said, a development version may required more maintenance and are updated more often.  Also, from the point of view of someone who wants to build an application, I'm not sure why a baseimage based on a development distro would be taken over one based on a stable release.

2018-06-08 11:10 UTC, rollbrettler commented
Fair enough, I updated the PR.

2018-06-11 12:05 UTC, jlesage requested changes
Before merging this, I just have a small change request.  Thanks!

2018-06-11 12:05 UTC, jlesage commented on Dockerfile.debian
> +    add-pkg --virtual build-dependencies curl gnupg ca-certificates patch && \
I think `gnupg` is not needed.  Could you remove it?

2018-07-13 13:58 UTC, jlesage commented
Closing this pull request, since we now have images based on debian 9.

2018-07-13 13:58 UTC, closed without merging